### ISSUE TITLE
isDrawn crash

### ISSUE THREAD

**Issue by TheStarlessAbstract** [TheStarlessAbstract/taintbynumbot#12]
2022-11-12T23:19:17.437593+00:00 app[worker.1]: TypeError: Cannot set properties of undefined (setting 'isDrawn')
2022-11-12T23:19:17.437594+00:00 app[worker.1]:     at response (/app/bot-commands.js:826:25)
2022-11-12T23:19:17.437595+00:00 app[worker.1]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2022-11-12T23:19:17.437595+00:00 app[worker.1]:     at async /app/bot-chatclient.js:125:20

**Comment by TheStarlessAbstract** [comment]
2022-11-12T23:22:46.639911+00:00 app[api]: Scaled to web@0:Free worker@1:Free by user thestarlessabstract@gmail.com
2022-11-12T23:23:25.871982+00:00 app[worker.1]: /app/bot-commands.js:826
2022-11-12T23:23:25.871993+00:00 app[worker.1]: 						cardDrawn.isDrawn = true;
2022-11-12T23:23:25.871993+00:00 app[worker.1]: 						                  ^
2022-11-12T23:23:25.871995+00:00 app[worker.1]: 
2022-11-12T23:23:25.871996+00:00 app[worker.1]: TypeError: Cannot set properties of undefined (setting 'isDrawn')
2022-11-12T23:23:25.871999+00:00 app[worker.1]:     at response (/app/bot-commands.js:826:25)
2022-11-12T23:23:25.872000+00:00 app[worker.1]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2022-11-12T23:23:25.872000+00:00 app[worker.1]:     at async /app/bot-chatclient.js:125:20
