### ISSUE TITLE
!points given to user

### ISSUE THREAD

**Issue by TheStarlessAbstract** [TheStarlessAbstract/taintbynumbot#13]
2022-11-12T23:26:28.651089+00:00 app[worker.1]: 						user.points += Number(newPoints);
2022-11-12T23:26:28.651090+00:00 app[worker.1]: 						^
2022-11-12T23:26:28.651091+00:00 app[worker.1]: 
2022-11-12T23:26:28.651092+00:00 app[worker.1]: TypeError: Cannot read properties of null (reading 'points')
2022-11-12T23:26:28.651092+00:00 app[worker.1]:     at response (/app/bot-commands.js:973:7)
2022-11-12T23:26:28.651093+00:00 app[worker.1]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2022-11-12T23:26:28.651093+00:00 app[worker.1]:     at async /app/bot-chatclient.js:125:20

**Comment by TheStarlessAbstract** [comment]
Fixed
